#!/usr/bin/env zsh

if [[ -f "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh" ]]; then
  source "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"
fi

if [[ -f "$HOME/.nix-profile/etc/profile.d/flatpak.sh" ]]; then
  source "$HOME/.nix-profile/etc/profile.d/flatpak.sh"
fi

# id
export USER_GID="$(id -g)"
export USER_UID="$(id -u)"

# release
export LSB_RELEASE_ID="$(lsb_release -si)"

export USER_APPS_HOME="$HOME/.local/apps"

# zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
