[general]
import = [
  "everforest-dark-hard.toml"
  #"everforest-dark-medium.toml"
  #"everforest-light-hard.toml"
]

[env]
TERM = "xterm-256color"

[font]
bold = { style = "ExtraBold" }
bold_italic = { style = "ExtraBoldItalic" }
italic = { style = "SemiBoldItalic" }
normal = { family = "JetBrainsMonoNL Nerd Font Mono", style = "SemiBold" }
size = 12.5

[window]
dynamic_padding = true
