#!/usr/bin/env zsh

alias e="$EDITOR"

alias ls="ls --color=auto"
alias ll="ls -al"

alias g="git"
alias gr='cd $(git rev-parse --show-toplevel)'

alias start-phenom="ssh pi -f 'wakeonlan $MAC_ADDR_PHENOM'"
alias start-remote-phenom="ssh remote-pi -f 'wakeonlan $MAC_ADDR_PHENOM'"
alias start-ryzen="ssh pi -f 'wakeonlan $MAC_ADDR_RYZEN'"
alias start-remote-ryzen="ssh remote-pi -f 'wakeonlan $MAC_ADDR_RYZEN'"
